Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.provision "shell", inline: "su"
  config.vm.provision "shell", inline: "sudo echo '123456' | passwd --stdin root "
  # config.vm.provision "shell", inline: "echo 'LC_ALL=en_US.utf-8' >> /etc/locale.conf"
 

  config.vm.define "es1" do |es1|
    es1.vm.box = "centos/7"
    es1.vm.box_version = "1811.02"
    es1.vm.network "private_network", ip: "192.168.30.11"
    es1.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

end